### PR TITLE
Remove questionmark from fixture filename

### LINKED ISSUE #48: Error extracting file `?limit=1-get.json` via composer on Windows OS.
## Issue
In Omise-PHP, there has one test file that the name is [`?limit=1-get.json`](https://github.com/omise/omise-php/blob/master/tests/fixtures/api.omise.co/customers/cust_test_5234fzk37pi2mz0cen3/cards/%3Flimit%3D1-get.json) which is, Windows OS doesn't support `?` sign on a filename.
It would make an error like below (or similar as below) when you try run `composer install` or `composer update`
```
Package operations: 1 install, 0 updates, 0 removals
  - Installing omise/omise-php (dev-master d68cb6b)
    Cloning d68cb6b12e9f7884f47c50f51a2a9b0d53b46e1b from cache
    d68cb6b12e9f7884f47c50f51a2a9b0d53b46e1b is gone (history was rewritten?)
    Failed to download omise/omise-php from source: Failed to execute git checkout "d68cb6b12e9f7884f47c50f51a2a9b0d53b46e1b" -- && git reset --hard "d68cb6b12e9f7884f47c50f51a2a9b0d53b46e1b" --

Note: checking out 'd68cb6b12e9f7884f47c50f51a2a9b0d53b46e1b'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at d68cb6b... Merge pull request #42 from oaattia/add_phpunit_conf
error: unable to create file tests/fixtures/api.omise.co/customers/cust_test_5234fzk37pi2mz0cen3/cards/?limit=1-get.json: Invalid argument
fatal: Could not reset index file to revision 'd68cb6b12e9f7884f47c50f51a2a9b0d53b46e1b'.
```

> Note: this issue would happen to all windows users.

**tested on**: Windows 10

## Workaround
For **Windows user**, I'd recommended that please download Omise-PHP directly from the link below.
https://github.com/omise/omise-php/archive/master.zip

..
Sorry for any inconvenience 🙇  . 
Nam

### PR DESCRIPTION
**Pull request by iwat**
1. Objective

To remove fixture file that contains question mark "?" in its name. This may cause an error on Windows platform and make `composer` failure.

2. Description of change

The previous code use path of the request to generate fixture file, but it took a query string into a part of filename, including question mark "?". This pull request changes that by encoding query string into base64 with [filename safe alphabet (RFC 4648)](https://tools.ietf.org/html/rfc4648#section-5) customization. The final file name looks like this: `cards-bGltaXQ9MQ-get.json`

3. Quality assurance

🔧 Environments:

tested on PHP version 5.3.29, 5.6.30, 7.0.16.

✏️ Details:

    docker run --rm -it -v `pwd`:/usr/src/app -w /usr/src/app php:5.3 ./vendor/bin/phpunit tests
    docker run --rm -it -v `pwd`:/usr/src/app -w /usr/src/app php:5.6 ./vendor/bin/phpunit tests
    docker run --rm -it -v `pwd`:/usr/src/app -w /usr/src/app php:7.0 ./vendor/bin/phpunit tests

4. Impact of the change

No feature, behavior, method signature impact. Fixes #48 and #41

5. Priority of change

Moderate ~ All windows customer

6. Additional Notes

No.

### CODE REVIEW

File: lib/omise/res/OmiseApiResource.php [hunk 1]
```diff
@@ -203,7 +203,15 @@ private function _executeTest($url, $requestMethod, $key, $params = null)
         $request_url = preg_replace('#^(http|https)://#', '', $url);
 
         // Remove slash if it had in last letter.
-        $request_url = rtrim($request_url, '/');
+        $parsed = parse_url($request_url);
```
Comment (guzzilar) [inline lib/omise/res/OmiseApiResource.php]: @iwat Saw that we can also remove the above line 
```php
$request_url = preg_replace('#^(http|https)://#', '', $url);
```
and use `$parsed['host']` from the parsed component at `$parsed = parse_url($url);` instead.

Comment (iwat) [inline lib/omise/res/OmiseApiResource.php]: Good idea, change is on the way.

File: lib/omise/res/OmiseApiResource.php [hunk 2]
```diff
@@ -199,11 +199,16 @@ private function _executeCurl($url, $requestMethod, $key, $params = null)
      */
     private function _executeTest($url, $requestMethod, $key, $params = null)
     {
-        // Remove Http, Https protocal from $url (string).
-        $request_url = preg_replace('#^(http|https)://#', '', $url);
-
         // Remove slash if it had in last letter.
```
Comment (guzzilar) [inline lib/omise/res/OmiseApiResource.php]: @iwat a last small point here, since we removed the previous implementation, I think this comment is not reflect to the current implementation much, shall we remove? 

LGTM for the rest 👍

Comment (iwat) [inline lib/omise/res/OmiseApiResource.php]: Nice, updating comment.

**Comment by guzzilar** [comment]
Nice! 👍
